Polynomial Class Reference
represents the polynomial as a linked list of terms
#include <poly.h>
Public Member Functions
Polynomial ()
~Polynomial ()
Polynomial (const Polynomial &rhs)
Polynomial (const double rhs)
Polynomial (const double coef, const unsigned deg)
Polynomial & operator= (const Polynomial &rhs)
void insert (term *t)
void insert (double coef, unsigned deg)
const Polynomial operator+ (const Polynomial &rhs) const
Polynomial operator- (const Polynomial &rhs) const
Polynomial & operator-= (const Polynomial &rhs)
Polynomial operator* (const Polynomial &rhs) const
Polynomial & operator*= (const Polynomial &rhs)
Polynomial operator- () const
double operator() (double a) const
Polynomial & operator+= (const Polynomial &rhs)
Polynomial abs () const
Polynomial antiderivative () const
Polynomial derivative () const
Friends
std::istream & operator>> (std::istream &is, Polynomial &p)
std::ostream & operator<< (std::ostream &os, const Polynomial &p)
Classes
class term
Detailed Description
represents the polynomial as a linked list of terms
Definition at line 14 of file poly.h.
Constructor & Destructor Documentation
Polynomial::Polynomial ()
default constructor, gives the zero polynomial
default constructor, returns a zero polynomial
Definition at line 33 of file poly.cc.
33                       {
34   // get the zero term
35   polynomial = new term(0.0, 0);
36 }
Polynomial::~Polynomial ()
default destructor
delete each term before expiring
Definition at line 47 of file poly.cc.
47                        {
48   term * t;
49   while(polynomial){
50     t = polynomial;
51     polynomial = t->next;
52     delete t;
53   }
54 }
Polynomial::Polynomial (const Polynomial & rhs)
copy constructor
Definition at line 268 of file poly.cc.
References insert(), and polynomial.
268                                            {
269   term * t;
270   // initialize
271   polynomial = new term();
272   // copy
273   t = rhs.polynomial;
274   while(t){
275     insert(t->coef, t->deg);
276     t = t->next;
277   }
278 }
Polynomial::Polynomial (const double rhs)
allow promotions
Definition at line 38 of file poly.cc.
38                                       {
39   polynomial = new term(rhs,0);
40 }
Polynomial::Polynomial (const double coef, const unsigned deg)
allow construction of monomials
Definition at line 42 of file poly.cc.
42                                                            {
43   polynomial = new term(coef, deg);
44 }
Member Function Documentation
Polynomial & Polynomial::operator= (const Polynomial & rhs)
assignment operator
Definition at line 259 of file poly.cc.
259                                                        {
260   if(this != &rhs){
261     Polynomial tmp(rhs);
262     swap(tmp);
263   }
264  return *this;
265 }
void Polynomial::insert (term * t)
add a term to the list
insert : add to list & reduce insert is in degree order polynomial is maintained in sorted order reduce only combines like terms.
Definition at line 61 of file poly.cc.
61                                {
62   term * u = polynomial;
63   term * prev = NULL;
64   while(u->next && ( t->deg > u->deg)){
65     prev = u;
66     u = u->next;
67   }
68   if (u == polynomial && !(t->deg >= u->deg)){
69     //still at head of list, and t is not bigger
70     polynomial = t;
71     t->next = u;
72   }  else if (t->deg > u->deg){
73     // got to end of list
74     u->next = t;
75   }
76   else {
77     // in the middle
78     t->next = u;;
79     if(prev)
80       prev->next = t;
81     else polynomial = t;
82   }
83   reduce();
84   return;
85 }
void Polynomial::insert (double coef = 0, unsigned deg = 0)
insert : doesn't require user to call constructor for term
Definition at line 88 of file poly.cc.
References insert().
88                                                     {
89   term * t = new term(coef, deg);
90   insert(t);
91   return;
92 }
const Polynomial Polynomial::operator+ (const Polynomial & rhs) const
addition operator
Definition at line 108 of file poly.cc.
109 {
110   Polynomial tmp(*this);
111   tmp += rhs;
112   return tmp;
113 }
Polynomial Polynomial::operator- (const Polynomial & rhs) const
subtraction operator
subtraction operator add -rhs
Definition at line 187 of file poly.cc.
187                                                             {
188   return *this + -rhs;
189 }
Polynomial & Polynomial::operator-= (const Polynomial & rhs)
subtraction/assignment operator
Definition at line 191 of file poly.cc.
191                                                         {
192   *this += (-rhs);
193   return *this;
194 }
Polynomial Polynomial::operator* (const Polynomial & rhs) const
multiplication operator
Definition at line 154 of file poly.cc.
References insert().
154                                {
155   // for each term in rhs
156   // multiply terms by coef and raise power by deg
157   Polynomial p;
158   term * u;
159   term * t = rhs.polynomial;
160   while (t) {
161     u = polynomial;
162     while(u){
163       p.insert(u->coef * t->coef, u->deg + t->deg);
164       u = u->next;
165     }
166     t = t->next;
167   }
168   return p;
169 }
Polynomial & Polynomial::operator*= (const Polynomial & rhs)
multiplication/assignment operator
Definition at line 171 of file poly.cc.
171                                                         {
172   *this = *this * rhs;
173   return *this;
174 }
Polynomial Polynomial::operator- () const
unary negation
unary negation operator just multiply by a scalar -1
Definition at line 179 of file poly.cc.
References operator*().
180 {
181   return this->operator*(-1.0);
182 }
double Polynomial::operator() (double a) const
polynomial evaluation at a point a
evaluate at point a
Definition at line 117 of file poly.cc.
References polynomial.
118 {
119   Polynomial p;
120   term *t, *u;
121   unsigned degree;
122   double result = 0;
123   // first reverse order the list
124   // since the polynomial is sorted,
125   // just peel off to the front each time.
126   t = polynomial;
127   while (t){
128     u =  p.polynomial;
129     p.polynomial = new term(*t);
130     t = t->next;
131     p.polynomial->next = u;
132   }
133   // seed with the highest order term
134   t = p.polynomial;
135   degree = t->deg;
136   // now evaluate the polynomial at a
137   while(t){
138     // multiply result by a
139     while(degree > t->deg){
140       result *= a;
141       degree--;
142     }
143     // add next coefficient
144     result += t->coef;
145     //remember depth (there might be gaps)
146     degree = t->deg;
147     // advance
148     t = t->next;
149   }
150   return result;
151 }
Polynomial & Polynomial::operator+= (const Polynomial & rhs)
addition/assignment
Definition at line 94 of file poly.cc.
References insert(), and polynomial.
95 {
96   Polynomial tmp(*this);
97   term * t = other.polynomial;
98   while(t){
99     tmp.insert(t->coef,t->deg);
100     t=t->next;
101   }
102   swap(tmp);
103   return *this;
104 }
Polynomial Polynomial::abs () const
make all coefficients positive
Definition at line 213 of file poly.cc.
References polynomial.
213                                 {
214   Polynomial tmp(*this);
215   term *t = tmp.polynomial;
216   while(t){
217     if (t->coef <  0)
218       t->coef *= -1;
219     t = t->next;
220   }
221   return tmp;
222 }
Polynomial Polynomial::antiderivative () const
general antiderivative with no arbitrary constant. Really, the arbitrary constant is zero here. by ignoring the constant we lose any meaningful result from antiderivative(0) which would have been a constant, but chooses 0 hence applying twice to 0, which would have been an arbitrary constant times x + another arbitrary constant, gives 0 for both constants, and looks like 0 again
Definition at line 230 of file poly.cc.
References insert().
230                                             {
231   Polynomial p;
232   term *t = polynomial;
233   while(t){
234     if(t->deg == 0)
235       p.insert(t->coef, 1);
236     else
237       p.insert( t->coef /(1.0+ t->deg), t->deg+1);
238     t=t->next;
239   }
240   return p;
241 }
Polynomial Polynomial::derivative () const
derivative as a polynomial
Definition at line 196 of file poly.cc.
References insert().
196                                         {
197   Polynomial p;
198   term *t = polynomial;
199   while(t){
200     if(t->deg)
201       p.insert((t->coef * t->deg), t->deg - 1);
202     t = t->next;
203   }
204   return p;
205 }
Friends And Related Function Documentation
std::istream& operator>> (std::istream & is, Polynomial & p) [friend]
extraction operator to read polynomials
extraction operator get a pair of numbers double, unsigned from an istream This might not be the best way to do this, and is nowhere used.
Definition at line 340 of file poly.cc.
340                                                      {
341   double coef;
342   unsigned int  degree;
343   Polynomial::term *t;
344   coef = 0.0;
345   while (coef == 0.0){
346     is>>coef;
347     is>>degree;
348     if(!is.fail()){
349       t = new Polynomial::term(coef, degree);
350       p.insert(t);
351     }
352   }
353   return is;
354 }
std::ostream& operator<< (std::ostream & os, const Polynomial & p) [friend]
insertion operator to print polynomials
operator<< insert polynomial into an output stream terms will be printed in order of increasing degree
Definition at line 309 of file poly.cc.
309                                                            {
310   Polynomial::term * t;
311   t = p.polynomial;
312   bool first = true;
313   while(t){
314     if(t->coef != 0.0){
315       if(!first)
316     os<<" + ";
317 
318       os<< t->coef;
319       if(t->deg){
320     os<<"*x";
321     if(t->deg > 1)
322       os<<"^"<<t->deg;
323       }
324       //    os<<" ";
325     first = false;
326    }
327     t = t->next;
328 
329   }
330   if (first)
331     os<<"0";
332   return os;
333 }
The documentation for this class was generated from the following files:
poly.h
poly.cc