poly.h File Reference
Declaration of the polynomial class.
#include <iostream>
Classes
class Polynomial
represents the polynomial as a linked list of terms
class Polynomial::term
Functions
Polynomial abs (const Polynomial &p)
Polynomial derivative (const Polynomial &p)
Polynomial antiderivative (const Polynomial &p)
Detailed Description
Declaration of the polynomial class.
Author: Daniel Uber
Definition in file poly.h.
Function Documentation
Polynomial abs (const Polynomial & p)
Returns: absolute value of polynomial
Definition at line 226 of file poly.cc.
References Polynomial::abs().
226                                    {
227   return p.abs();
228 }
Polynomial antiderivative (const Polynomial & p)
Returns: indefinite integral of p with constant 0
Definition at line 245 of file poly.cc.
References Polynomial::antiderivative().
245                                                 {
246   return p.antiderivative();
247 }
Polynomial derivative (const Polynomial & p)
return polynomial derivative
Definition at line 209 of file poly.cc.
References Polynomial::derivative().
209                                            {
210   return p.derivative();
211 }