poly.cc File Reference
Implementation for the polynomial class.
#include `poly.h`
#include <cstring>
Functions
Polynomial derivative (const Polynomial &p)
Polynomial abs (const Polynomial &p)
Polynomial antiderivative (const Polynomial &p)
std::ostream & operator<< (std::ostream &os, const Polynomial &p)
std::istream & operator>> (std::istream &is, Polynomial &p)
Detailed Description
Implementation for the polynomial class.
Author: Daniel Uber
Definition in file poly.cc.
Function Documentation
abs (const Polynomial & p)
Returns: absolute value of polynomial
Definition at line 226 of file poly.cc.
References Polynomial::abs().
226                                    {
227   return p.abs();
228 }
antiderivative (const Polynomial & p)
Returns: indefinite integral of p with constant 0
Definition at line 245 of file poly.cc.
References Polynomial::antiderivative().
245                                                 {
246   return p.antiderivative();
247 }
derivative (const Polynomial & p)
return polynomial derivative
Definition at line 209 of file poly.cc.
References Polynomial::derivative().
209                                            {
210   return p.derivative();
211 }
std::ostream& operator<< (std::ostream & os, const Polynomial & p)
operator<< insert polynomial into an output stream terms will be printed in order of increasing degree
Definition at line 309 of file poly.cc.
References Polynomial::polynomial.
309                                                            {
310   Polynomial::term * t;
311   t = p.polynomial;
312   bool first = true;
313   while(t){
314     if(t->coef != 0.0){
315       if(!first)
316     os<<" + ";
317 
318       os<< t->coef;
319       if(t->deg){
320     os<<"*x";
321     if(t->deg > 1)
322       os<<"^"<<t->deg;
323       }
324       //    os<<" ";
325     first = false;
326    }
327     t = t->next;
328 
329   }
330   if (first)
331     os<<"0";
332   return os;
333 }
std::istream& operator>> (std::istream & is, Polynomial & p)
extraction operator get a pair of numbers double, unsigned from an istream This might not be the best way to do this, and is nowhere used.
Definition at line 340 of file poly.cc.
References Polynomial::insert().
340                                                      {
341   double coef;
342   unsigned int  degree;
343   Polynomial::term *t;
344   coef = 0.0;
345   while (coef == 0.0){
346     is>>coef;
347     is>>degree;
348     if(!is.fail()){
349       t = new Polynomial::term(coef, degree);
350       p.insert(t);
351     }
352   }
353   return is;
354 }