#makefile
#Daniel Uber
# MCS 360 Week 8 Quiz

run: linkedListNoHeader/main
	linkedListNoHeader/main

linkedListNoHeader/main:
	$(MAKE) -C linkedListNoHeader

clean:
	$(MAKE) -C linkedListNoHeader clean
