#makefile
#Daniel Uber MCS 360 Week 10 Quiz
all: week10quiz
week10quiz: mergesort.cc
	g++ -g -std=c++0x -Wall -Werror -o week10quiz mergesort.cc

run: week10quiz
	./week10quiz

clean:
	rm -f week10quiz *~
